### ISSUE TITLE
Unauthorized 401

### ISSUE THREAD

**Issue by Krata4** [SpawnY0815/mb-connect-openhab#5]
Hello,

I am getting Unauthorized 401. 
Propably VIN issue. I ca autorize via OAUTH2 and generate Access Token but when I call https://api.mercedes-benz.com/vehicledata/v2/vehicles/myVIN/resources I got Unauthorized 401.

Can you help me please?

Thanks
Jirka

**Comment by SpawnY0815** [comment]
Hey @Krata4 ,

Please double check your credentials and VIN. If you are trying to load images also check the API_Key.

In addition, please check again all registered services in the mercedes console.

The error looks like you have no services logged in. Please have a look at my description again.

I don't have much time at the moment. I will possibly have a look at it this weekend, should you contact me again. But I can not promise this.

Cheers!
Chris
