### ISSUE TITLE
Persistance (MariaDB)

### ISSUE THREAD

**Issue by ChR-iSz** [SpawnY0815/mb-connect-openhab#6]
Hi, thanks for you great work. The Addon works fine, but i have one question.

After every restart OpenHab 3 i must go to the credentials website, add key, vin, etc. and press the authenticate button.

How can i store this ? Have you a short step list for me, how can i store the three variables for safe reboot ?

**Comment by SpawnY0815** [comment]
Hey @ChR-iSz ,

thank you!
You need an openHAB persistence service, like mapDB. This is a openHAB service and not related to my script.
Check it out here: https://www.openhab.org/docs/tutorial/persistence.html

**Comment by ChR-iSz** [comment]
Thanks for replay,

Yes, i know. I have installed MariaDB-Persistance Addon. Connection to DB works fine in syslog, but the keys are NULL after restart Openhab.

Dont know what i have forget to configure... 😔

**Comment by SpawnY0815** [comment]
Are there some other items values stored in the MariaDB? Pls double check if this solution works at all. Maybe try the mapdb first, its very easy to setup.

**Comment by ChR-iSz** [comment]
Hi Spawn,

Thanks. Will try now... 👍
